language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  - DEPS="stable"
  - DEPS="dev"

cache:
  directories:
    - $HOME/.composer/cache

# Set up the project for testing
before_script:
  - if [[ $DEPS = 'lowest' ]]; then composer update -n --prefer-dist --prefer-lowest; fi
  - if [[ $DEPS = 'stable' ]]; then composer update -n --prefer-dist --prefer-stable; fi
  - if [[ $DEPS = 'dev' ]]; then composer update -n --prefer-dist; fi

# Run Tests
script:
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml

# Process results
after_script:
  # Send code coverage to scrutinizer-ci.com & coveralls.io
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover  build/logs/clover.xml
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar

# Build Matrix
matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: DEPS="lowest"
    - php: 7.0
      env: DEPS="lowest"

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
